dist: trusty
language: node_js
node_js:
  - "7"
addons:
  postgresql: "9.4"
  chrome: stable
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -U postgres -d semester3 -f travis/travis.sql
  - psql -c 'create database semester3;' -U postgres
  - sudo chown -R travis ./travis/express.sh
  - sudo chmod +x ./travis/express.sh
  - ./travis/express.sh
script:
  - ng e2e
