dist: trusty
language: node_js
node_js:
  - "7"
addons:
  postgresql: "9.4"

services:
    - postgresql
before_script:
  - psql -c 'create database semester3;' -U postgres
  - psql -U postgres -d semester3 -f appTest/travis.sql
  - git clone --depth=50 --branch=master https://github.com/arminbeiner/ExpressDB.git arminbeiner/ExpressDBall
install:
  - npm install
script:
  - ng test
